### ISSUE TITLE
issue when running inc2prev

### ISSUE THREAD

**Issue by albertosanchezmarroquin** [epiforecasts/inc2prev#35]
Hello, 

We are trying to run inc3prev within the epi ensamble team. We managed to make it work up to the point when we run the estimate.R -d 1 script, where we get the following error: 

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error: CallrFuture (future_lapply-1) failed. The reason reported was ‘callr subprocess failed: there is no package called ‘inc2prev’’. Post-mortem diagnostic: The parallel worker (PID 5917) started at 2022-04-13T14:14:12+0000 finished with exit code 0. Detected a non-exportable reference (‘externalptr’) in one of the globals (‘future.call.arguments’ of class ‘DotDotDotList’) used in the future expression. The total size of the 9 globals exported is 2.41 MiB. The three largest globals are ‘future.call.arguments’ (2.38 MiB of class ‘list’), ‘...future.FUN’ (18.01 KiB of class ‘function’) and ‘convert_to_weekly’ (10.34 KiB of class ‘function’)
Execution halted

Is there any suggestion on what we could try to fix it? 

Thank you very much for your help. 

Alberto

**Comment by seabbs** [comment]
Have you been able to use `simple-example.R` to produce one fit of the model? 

Your error message is quite cryptic but it sounds like the parallel process has not found the `inc2prev` code which is odd as it is loaded in the script. 

Do you have `devtools` installed (responsible for loading the package here)? Otherwise, it might be a package version of environment issue. Where are you running this/with what? 

Sam

**Comment by sbfnk** [comment]
Can you try pulling the latest version and install the R package included using
```r
remotes::install_github("epiforecasts/inc2prev")
```
and then try running the script again?

**Comment by sbfnk** [comment]
I assume this has been resolved.
